import Link from "next/link";
import { FileText, Download } from "lucide-react";

import { listReports } from "@/lib/data";
import { Card, CardContent } from "@/components/ui/card";

export const metadata = {
  title: "Reports & archive",
  description: "Final scorecards, methodology report, raw scorecards, and the investor PDF.",
};

const TITLES: Record<string, { title: string; blurb: string }> = {
  FINAL_REPORT: {
    title: "Final scorecards",
    blurb: "Top-K survivors of the 102-variant search, with per-gate evaluation.",
  },
  REPORT: {
    title: "Methodology report",
    blurb: "Search design, cost model, walk-forward folds, diagnostics, and what passes.",
  },
  SCORECARD_rotation: {
    title: "Rotation scorecard",
    blurb: "Raw 12-gate scorecard for the rotation winner with all diagnostic rows.",
  },
  DEPLOYMENT_FRAMEWORK: {
    title: "Deployment framework v1.0",
    blurb: "The 12 gates and 6 kill triggers that gate live deployment.",
  },
};

export default async function ReportsPage() {
  const reports = await listReports();
  return (
    <div className="space-y-6 fade-rise">
      <header className="space-y-2 max-w-3xl">
        <p className="text-[11px] font-semibold uppercase tracking-[0.18em] text-[var(--color-brand-gold-700)]">
          Archive
        </p>
        <h1 className="font-heading text-3xl sm:text-4xl">Reports &amp; raw artifacts</h1>
        <p className="text-sm sm:text-base text-muted-foreground leading-relaxed">
          Markdown reports generated by the research pipeline. Every number on this
          portal reconciles to one of these files (and to the CSVs / JSONs in <code className="text-xs bg-muted px-1.5 py-0.5 rounded">results/</code>).
        </p>
      </header>

      <div className="grid gap-4 sm:grid-cols-2">
        {reports.map((slug) => {
          const meta = TITLES[slug] ?? { title: slug, blurb: "" };
          return (
            <Card key={slug}>
              <CardContent className="py-5 space-y-3">
                <div className="flex items-start gap-3">
                  <div className="size-10 rounded-md flex items-center justify-center bg-[var(--color-brand-navy)] text-[var(--color-brand-gold)]">
                    <FileText className="size-4" aria-hidden />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h2 className="font-heading text-lg leading-tight">{meta.title}</h2>
                    <p className="text-xs text-muted-foreground mt-0.5">{meta.blurb}</p>
                  </div>
                </div>
                <Link
                  href={`/reports/${slug}/`}
                  className="inline-flex items-center gap-1 text-sm text-[var(--color-brand-gold-700)] hover:text-[var(--color-brand-gold)] focus:outline-none focus-visible:ring-2 focus-visible:ring-ring rounded-sm"
                >
                  Open report →
                </Link>
              </CardContent>
            </Card>
          );
        })}
        <Card>
          <CardContent className="py-5 space-y-3">
            <div className="flex items-start gap-3">
              <div className="size-10 rounded-md flex items-center justify-center bg-[var(--color-brand-gold)] text-[var(--color-brand-navy)]">
                <Download className="size-4" aria-hidden />
              </div>
              <div className="flex-1 min-w-0">
                <h2 className="font-heading text-lg leading-tight">Investor PDF</h2>
                <p className="text-xs text-muted-foreground mt-0.5">
                  13-page printed proposal — branded, paginated, suitable for share.
                </p>
              </div>
            </div>
            <a
              href="/BursaHack_Proposal.pdf"
              className="inline-flex items-center gap-1 text-sm text-[var(--color-brand-gold-700)] hover:text-[var(--color-brand-gold)]"
              download
            >
              Download PDF →
            </a>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
